### ISSUE TITLE
定期デプロイジョブの実行

### ISSUE THREAD

**Issue by quietsato** [quietsato/wakazeit#4]
GitHub Actions等を用いてVercelのデプロイジョブを呼び出す

**Comment by 0x307e** [comment]
Vercel ってそもそも現状 master への push と同時にデプロイ走るはずだから特に意味ない気がする

**Comment by quietsato** [comment]
表示させている情報は`getStaticProps`でビルド時に取得したものなので、情報の更新のためにビルドを走らせてあげる必要がある

**Comment by 0x307e** [comment]
そうだとしても定期的にビルドし直すのはなんか微妙なソリューションな気がする

**Comment by 0x307e** [comment]
`pages/api` にデータまとめてフェッチする API 作って、その API で WakaTime の API 叩くと認証情報漏らさずにリアルタイム更新できるのでは？と思った。

**Comment by quietsato** [comment]
https://nextjs.org/docs/basic-features/data-fetching#getstaticprops-static-generation

WakaTime側のデータ更新がそこまで頻繁ではない（だいたい15分間隔）ので、getStaticPropsにrevalidateを指定する方策でやれば、WakaTimeへのアクセスは最小限に抑えられそうな気がする。

**Comment by 0x307e** [comment]
ISR みたいなやつか
それは割と行けそうな気がする

**Comment by quietsato** [comment]
OK👍
これでやってみる
